url: "https://radicle.xyz"
baseurl: "/"

plugins:
  - jekyll-feed

collections:
  guides:
    output: true
    permalink: /guides/:path/
  pages:
    output: true
    permalink: /:path/
  rips:
    output: true
    permalink: /rip/:path/


highlighter: rouge
markdown: kramdown
kramdown:
  syntax_highlighter: rouge

exclude:
  - .jj
  - Makefile
  - LICENSE
  - flake.*
  - README.md
include:
  - _redirects
  - .well-known

# Metadata
title: "Radicle: the sovereign forge"
description: "The Radicle forge is an open source, peer-to-peer code collaboration stack built on Git."
fedi: "@radicle@toot.radicle.xyz"
node: "seed.radicle.xyz"

# jekyll-feed configuration
feed:
  icon: /assets/images/logo-small.svg

defaults:
  - scope:
      path: _guides
    values:
      layout: guide
  - scope:
      path: _pages
    values:
      layout: page
  - scope:
      path: _posts
    values:
      layout: post
  - scope:
      path: _rips
    values:
      layout: rip
